1 :
   nom : "Agenda"
   nomClasse : "agenda.application.Agenda"
   autorun : true
   defaultPlugin: true
   unique : false
2 :
   nom : "Crud Data Plugin"
   nomClasse : "agenda.tiers.CrudDataEvenement"
   interface: "agenda.application.interfaces.CrudDataInterface"
   autorun : true
   requirements : ["Agenda"]
   defaultPlugin: true
   unique : true
3 :
   nom : "Liste des events"
   nomClasse : "agenda.tiers.DisplayCardEvent"
   interface: "agenda.application.interfaces.DisplayInterface"
   autorun : false
   requirements : ["Agenda"]
   defaultPlugin: false
   position: "header"
   unique : false

4 :
   nom : "Tableau des events"
   nomClasse : "agenda.tiers.DisplayTabEvent"
   interface: "agenda.application.interfaces.DisplayInterface"
   autorun : false
   requirements : ["Agenda"]
   defaultPlugin: true
   position: "header"
   unique : false
5 :
   nom : "Nouveau evenement"
   nomClasse : "agenda.tiers.CreateEvent"
   interface: "agenda.application.interfaces.CreateInterface"
   autorun : false
   requirements : ["Agenda"]
   defaultPlugin: false
   position: "header"
   unique : false
   
6 :
   nom : "Enregistrer modification"
   nomClasse : "agenda.tiers.SaveUpdateDispalyCard"
   interface: "agenda.application.interfaces.IntegrableInterface"
   autorun : false
   requirements : ["Agenda"]
   defaultPlugin: true
   pluginIntegrable : ["Tableau des events"]
   position: "footer"
   unique : false
   
7 :
   nom : "Supprimer item"
   nomClasse : "agenda.tiers.DeleteItemDisplayCard"
   interface: "agenda.application.interfaces.IntegrableInterface"
   autorun : false
   requirements : ["Agenda","Tableau des events"]
   defaultPlugin: false
   pluginIntegrable : ["Tableau des events"]
   position: "footer"
   unique : false
   
8 :
   nom : "Moniteur"
   nomClasse : "agenda.moniteur.Moniteur"
   interface: ""
   autorun : true
   requirements : []
   defaultPlugin: true
   pluginIntegrable : []
   position: ""
   unique : false
 