1 :
   nom : "Agenda"
   nomClasse : "agenda.application.Agenda"
   interface: ""
   autorun : true
   params : []
   requirements : ["Test Plugin"]
   defaultPlugin: false
   headerButton: false

4 :
   nom : "Load Data Plugin"
   nomClasse : "agenda.tiers.LoadDataPlugin"
   interface: "agenda.application.interfaces.CrudDataInterface"
   autorun : false
   params : []
   requirements : []
   dependances : "Agenda"
   defaultPlugin: true
   headerButton: false
5 :
   nom : "Liste des events"
   nomClasse : "agenda.tiers.DisplayListEvent"
   interface: "agenda.application.interfaces.DisplayInterface"
   autorun : false
   params : []
   requirements : []
   dependances : "Agenda"
   defaultPlugin: false
   headerButton: true
6 :
   nom : "Tableau des events"
   nomClasse : "agenda.tiers.DisplayTabEvent"
   interface: "agenda.application.interfaces.DisplayInterface"
   autorun : false
   params : []
   requirements : []
   dependances : "Agenda"
   defaultPlugin: false
   headerButton: true
7 :
   nom : "Nouveau evenement"
   nomClasse : "agenda.tiers.CreateEvent"
   interface: "agenda.application.interfaces.CreateInterface"
   autorun : false
   params : []
   requirements : []
   dependances : "Agenda"
   defaultPlugin: false
   headerButton: true