1 :
   nom : "Agenda"
   nomClasse : "agenda.application.Agenda"
   interface: ""
   autorun : true
   params : []
   requirements : ["Test Plugin"]
   defaultPlugin: false
2 :
   nom : "Test Plugin"
   nomClasse : "agenda.tiers.TestPlugin"
   interface: "agenda.application.interfaces.DisplayInterface"
   autorun : false
   params : []
   requirements : []
   dependances : "Agenda"
   defaultPlugin: true
3 :
   nom : "Test Plugin 2"
   nomClasse : "agenda.tiers.TestPlugin2"
   interface: "agenda.application.interfaces.DisplayInterface"
   autorun : false
   params : []
   requirements : []
   dependances : "Agenda"
   defaultPlugin: false
4 :
   nom : "Load Data Plugin"
   nomClasse : "agenda.tiers.LoadDataPlugin"
   interface: "agenda.application.interfaces.CrudDataInterface"
   autorun : false
   params : []
   requirements : []
   dependances : "Agenda"
   defaultPlugin: true